### ISSUE TITLE
Missing Version 3.0 NuGet package

### ISSUE THREAD

**Issue by seangwright** [ctolkien/Slugify#19]
When I visit https://www.nuget.org/packages/Slugify.Core/ I cannot find the 3.0 version of the package that is mentioned in the README.md

Has it be published somewhere else?

**Comment by ctolkien** [comment]
Hi, no it hasn't yet been released - work is detailed here: https://github.com/ctolkien/Slugify/pull/16

It's probably good to go in... I've just been a bit hesitant, as I don't have much in the way of addressing any issues that may come in in the short term.

**Comment by seangwright** [comment]
Given the existing tests, what is the primary cause of perceived risk with the release? The large number of changes internally?

I think a major version bump is a clear sign that it should not be an auto-upgrade for consumers. At the same time, the 200 or so lines of the main class are easy enough for someone to step through (and make a PR for) if they identify an issue.

I'm currently using 2.3.0, which works great. Have you considered releasing 3.x tagged as a prelease in NuGet?

I'd be happy to consume it for the app I'm working on and let you know if I see issues.

**Comment by ctolkien** [comment]
@seangwright - v3 has just gone live. Give it a crack and let me know how you go
