### ISSUE TITLE
Problem with the letter 'Å'

### ISSUE THREAD

**Issue by FredMar** [ctolkien/Slugify#21]
I have a problem with the string "Å å Æ æ Ø ø" - the slug produced is "a-a-ae-ae-oe-oe" when it should be "aa-aa-ae-ae-oe-oe"

Heres is the code:

var config = new SlugHelperConfiguration();
config.StringReplacements.Add("Å", "AA");
config.StringReplacements.Add("å", "aa");
config.StringReplacements.Add("Æ", "AE");
config.StringReplacements.Add("æ", "ae");
config.StringReplacements.Add("Ø", "OE");
config.StringReplacements.Add("ø", "oe");            

SlugHelper helper = new SlugHelper(config);
var slug = helper.GenerateSlug("Å å Æ æ Ø ø");

Any solutions? :)

**Comment by MartinAmsinck** [comment]
Same issue

**Comment by ctolkien** [comment]
Assigning help wanted to both of these!
