### ISSUE TITLE
Slugify 4.0.0 is not showing up in nuget

### ISSUE THREAD

**Issue by cm-andrews** [ctolkien/Slugify#61]
Would it be possible to add V4 to nuget?

https://www.nuget.org/packages/Slugify.Core#versions-body-tab

Cant seem to get umlauts replacement working in V3 and I guess V4 fixes exactly that.

**Comment by ctolkien** [comment]
Yeah, blocked on: https://github.com/ctolkien/Slugify/issues/27

**Comment by ctolkien** [comment]
V4 has now hit NuGet!
<img width="600" alt="image" src="https://user-images.githubusercontent.com/515955/220607358-3f208448-2499-423e-a295-ce37433627b6.png">
