### ISSUE TITLE
Design a better logo

### ISSUE THREAD

**Issue by ctolkien** [ctolkien/Slugify#64]
I've put in something that is.. just anything more than having no logo

**Comment by ricardoboss** [comment]
Maybe take inspiration from other slugify projects: https://github.com/Pharaonic/php-slugify

**Comment by ctolkien** [comment]
![_ac18e4f3-2dd0-4d62-972c-d8a8a57405b9](https://user-images.githubusercontent.com/515955/228414461-ad1deece-743c-4dd4-b6b0-9a242230e45a.jpg)

This thing is cute. Generated from one of those AI generators.
